# Generated by Django 4.0 on 2023-01-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'sm'), ('md', 'md'), ('l', 'l'), ('xl', 'xl')], default='sm', max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SneakerImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.URLField()),
                ('image2', models.URLField()),
                ('image3', models.URLField()),
                ('image4', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'images',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('alt', models.TextField(default='sneaker image')),
                ('gender', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('all', 'all')], default='all', max_length=20)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('colors', models.ManyToManyField(max_length=2, to='sneakers.Color')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.sneakerimgs')),
                ('sizes', models.ManyToManyField(to='sneakers.Sizes')),
            ],
            options={
                'verbose_name': 'Sneaker',
                'verbose_name_plural': 'Sneakers',
            },
        ),
    ]
