# Generated by Django 4.0 on 2023-01-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='images',
            new_name='imgs',
        ),
    ]
